### ISSUE TITLE
일정 크기보다 작을 시 화면 오른편에 세로 줄이 생기는 문제

### ISSUE THREAD

**Issue by ghost** [DIMI19WP/codegen-ace#11]
일정 폰트 보다 작을 시 
화면 오른쪽에 회색 선이 세로로 생깁니다

ex) 크기가 '3'일 때 보임

그 선을 넘어서도 글자는 타이핑이 가능합니다

수정 부탁드립니다

**Comment by rycont** [comment]
미안해요 그건 제가 어쩔 수 없는, 에디터 디폴트 설정이여서ㅠㅠㅠ
