### ISSUE TITLE
설정안내 버튼 응답없음

### ISSUE THREAD

**Issue by ghost** [DIMI19WP/codegen-ace#12]
설정안내 버튼을 눌렀을 때
크롬 & 크로미움 엣지 모두 반응 없음

고쳐주세요 언니 ㅠㅜㅜ

**Comment by seungminio** [comment]
프로이슈러

**Comment by rycont** [comment]
💜💜

**Comment by rycont** [comment]
수정했어요~! 
https://github.com/ajaxorg/ace/wiki/Configuring-Ace
