### ISSUE TITLE
로드 후 ctr + c 오류

### ISSUE THREAD

**Issue by ghost** [DIMI19WP/codegen-ace#7]
로드 후 컨트롤 + C 하면
클립보드에 저장한 값이 아닌
기본 값인

#include <stdio.h>
int main() {
    
}

이 출력됨

위의 코드를 지우고 다시 컨트롤 씨를 하면
클립보드의 코드가 잘 입력됨

수정 부탁드립니다 ㅠㅜㅜ

**Comment by ghost** [comment]
형 이거 내가 잘못한거야
그 기본 값이 나오기 전에 내가 붙여넣기를 해서 그런 것 같어,,
기본 값을 아예 코드에서 삭제하든가
설정으로 띄우거나 안 띄울 수 있게 만들면 어떨까요,,,??
미안해 ㅠㅜㅠㅜㅠㅜ

**Comment by rycont** [comment]
적절하게 수정했습니다:) 기존에 입력된 코드가 있는 경우에는 그 코드가 출력되고 그렇지 않으면 #include랑 int main 들어가게 해놨어요
